version: "3.8"
services:
    nginx-exporter:
      image: nginx/nginx-prometheus-exporter:0.4.2
      #ports:
      #  - 9113
      command:
        - -nginx.scrape-uri
        # ip and port are comes from nginx config 
        #     server {
        #     listen 8001;
        #     location /stub_status {
        #         stub_status;
        #     }
        # }
        - http://nginx:8001/stub_status

networks:
  default:
    name: vnet
    external: true
