version: '3'
services:
  fluentd:
#    image: fluent/fluentd:latest
    build: .
    volumes:
      - ./fluent.conf:/fluentd/etc/fluent.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    links:
      - "elasticsearch"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "discovery.type=single-node"
    volumes:
      - ./esdata:/usr/share/elasticsearch/data


networks:
  default:
    name: vnet
    external: true
