version: '3.8'
services:
  alertmanager:
    image: prom/alertmanager:latest
    restart: unless-stopped
    ports:
      - "9093:9093"
    volumes:
      - "./alertmanager/:/etc/alertmanager"
      - "./alertmanager-data:/data"
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
networks:
  default:
    name: vnet
    external: true