version: "3.8"

services:
    prometheus:
        image: prom/prometheus
        ports:
           - "9990:9090"
        volumes:
           - ./data:/prometheus-data
           - ./prometheus.yml:/etc/prometheus/prometheus.yml
        command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

networks:
  default:
    name: vnet
    external: true