version: "3.8"

services:
    prometheus:
        image: prom/prometheus
        ports:
           - "9990:9090"
        volumes:
           - ./data:/prometheus-data
           - ./prometheus.yml:/etc/prometheus/prometheus.yml

networks:
     default:
         external:
             name: vnet
