global:
  scrape_interval: 10s

scrape_configs:
#  - job_name: "prometheus_master"
 #   scrape_interval: 5s
  #  static_configs:
   #   - targets: ["prometheus:9090"]
  - job_name: 'nginx_status'
    scrape_interval: 1m
    metrics_path: '/metrics'
    static_configs:
      - targets: ['nginx-exporter:9113']
  - job_name: 'moji'
    scrape_interval: 1m
    metrics_path: '/metrics'
    static_configs:
      - targets: ['pushgateway:9191']
  - job_name: pm2-metrics
    scrape_interval: 10s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['app:9209']
