version: "3.8"

services:
  loki:
    image: grafana/loki:2.6.1
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/loki-config.yaml
      - ./loki/data:/data/loki
    command: -config.file=/etc/loki/loki-config.yaml

  promtail:
    image: grafana/promtail:2.6.1
    restart: unless-stopped
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml
    command: -config.file=/etc/promtail/config.yml

  grafana:
    image: grafana/grafana
    ports:
      - 4000:3000
    environment:
      - GF_SERVER_ROOT_URL=http://0.0.0.0:3000
      - GF_SECURITY_ADMIN_PASSWORD=1
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./grafana-storage:/var/lib/grafana
    user: "472"

networks:
  default:
    name: vnet
    external: true
