version: "3.8"

services:
    grafana:
      image: grafana/grafana
      ports:
        - 4000:3000
      environment:
        - GF_SERVER_ROOT_URL=http://0.0.0.0:3000
        - GF_SECURITY_ADMIN_PASSWORD=1
      volumes:
        - ./grafana.ini:/etc/grafana/grafana.ini
        - ./grafana-storage:/var/lib/grafana
      user: '104'
networks:
  default:
    name: vnet
    external: true
