version: "3.8"

services:
  loki:
    image: grafana/loki:2.6.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.6.1
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml

  grafana:
    image: grafana/grafana
    ports:
      - 4000:3000
    environment:
      - GF_SERVER_ROOT_URL=http://0.0.0.0:3000
      - GF_SECURITY_ADMIN_PASSWORD=1
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./grafana-storage:/var/lib/grafana
    user: '472'

networks:
  default:
    name: vnet
    external: true
