version: "3.8"
pushgateway:
    image: prom/pushgateway
    command:
      - '--web.listen-address=:9191'
      - '--push.disable-consistency-check'
      - '--persistence.interval=5m'
    ports:
      - 9191:9191

networks:
    default:
      external:
          name: vnet
